### ISSUE TITLE
Build a Github Actions

### ISSUE THREAD

**Issue by Abdylk** [OpenFuturePlatform/open-state#10]
Since we have moved to Github, we need to make necessary pipelines to automate our workflows. 
To Do: 
1. Check the Gitlab CI (our Gitlab CI)
2. Design a Github Actions that meet our needs

**Comment by Abdylk** [comment]
@ruslanys Are there anything we need to consider while building a pipeline? If yes, please let us know.

**Comment by ruslanys** [comment]
First of all, reproduce the Gitlab build/test stage. Deployment is a low priority. The most critical ones – is everything before.
