### ISSUE TITLE
Add an ability to make calls (Webhook)

### ISSUE THREAD

**Issue by Abdylk** [OpenFuturePlatform/open-state#17]
We need to implement a logic that will send a web-hooks when OPEN State is triggered. The calls should me made to the prescribed URL. For more details, watch the videos of the meeting.

**Comment by trenatov** [comment]
1. Blockchain processor adds to queue in Redis (unique key, address, blockchain)
2. Webhook sender job polls an element, then tries to send webhook
 --> If webhook sending was not succesful, it adds to failed webhook queue
 --> If webhook sending was succesful, processes next one

3. Every given time a job wakes up which tries to resend failed webhooks.
 --> If it was unseccessful, then adds put failed queue again by incrementing retry count and last retry date

![Webhook architecture](https://user-images.githubusercontent.com/23068741/93608265-3d0bc100-f9ec-11ea-957c-14eef367a57b.png)

@ruslanys @layko-andrey Please review

**Comment by ruslanys** [comment]
I believe we need to arrange a call to discuss.

By the way, it would be nice if you can describe the architecture we implemented for tracking transactions. @Abdylk @trenatov

**Comment by Abdylk** [comment]
@ruslanys sounds like a plan. Have sent everyone invites for the meeting.

**Comment by layko-andrey** [comment]
Webhook invocation would be processed as separate task that awake time to time. It check collection with information about wallets and it's transactions and process HTTP request for each transaction.
When new transactions detected it would be savet to Mongo and added to collection of wallet's transactions in Redis. Information about webhook in vocation would savet in Mongo after each request. 
Each wallet and it's transactions would be processed in separate thread. In common webhook invocation process would be the following:
1. webhook invocation job go throught collection of wallets and looking for non-blocked wallet. If no such wallets job would sleep until next awake
2. for each blocked wallet chek last status update timestamp. If it's walue differ from current timestamp more than specified timeout, mark that wallet as non-blocked.
3. mark wallet as blocked if found and start it's processing in separate threead
4. for each wallet's transaction starting from oldest make HTTP request ( GET ). In case of success move to next transaction and update status update timestamp
5. in case of negative responce or timeout repeat current request after period of time. The period would be calculated as arithmetic progression
6. after n attempts of filed requests current wallet would be marked as failed and stop it's processing. These wallet would not be processed by another job. Cound of attempts ( n ) would be specified as settings parameter.
7. after success processing of all transactions unlock wallet.
