### ISSUE TITLE
Complete Wiki Pages 

### ISSUE THREAD

**Issue by Abdylk** [OpenFuturePlatform/open-state#18]
1. Need to create and complete pages for each feature we are adding to the Open State.
2. Need to keep the pages up to date. (Whenever we make changes or alter already discussed changes, need to update the wiki pages as well. 
The list of the pages so far: 
- Block-chain Tracking
- Webhook Invocation

Goal: 
1. Have a shared understanding between team members
2. On-board new team members to the project
3. Increase team's horizontal mobility. Meaning that any team member could take on any task. Thus, we wont depend on one person.

**Comment by ruslanys** [comment]
This story is a pretty abstract. We need to specify exact pages we need to complete.

**Comment by Abdylk** [comment]
@ruslanys my bad, i should have added the list of the specific pages.
