### ISSUE TITLE
Need to fix the exchange rate issue

### ISSUE THREAD

**Issue by Abdylk** [OpenFuturePlatform/open-state#19]
**Background of the issue:** 
We have been using a different API for converting the currencies into ethereum. Now they have changed their subscription plans and the API that we have been using turned out to be as PAID. 
**To do**
@trenatov has found a new API and we even have a plan to fix this issue. 
Need to replace that old API following the way we agreed with Temirlan. 
@trenatov Please share the details along with proposed plan of fixing that issue.

**Comment by ruslanys** [comment]
We need to move this issue to the OPEN-API project. https://github.com/OpenFuturePlatform/open-api

**Comment by Abdylk** [comment]
@ruslanys Done.
