### ISSUE TITLE
Create necessary repositories in Github

### ISSUE THREAD

**Issue by Abdylk** [OpenFuturePlatform/open-state#9]
Need to do the following within this task: 
1. Check the repos on Gitlab
2. If there are any missing repo in Github that we have in Gitlab, create that missing repo

**Comment by Abdylk** [comment]
@layko-andrey Need your help here.

**Comment by layko-andrey** [comment]
All missing repositories are migrated to GitHub. All missing environment variables migrated to GitHub secrets
